=== KolkaMeister/museum-defender/Assets/StreamingAssets/dialog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:HistoryTrip.Dialogs"
           xmlns="urn:HistoryTrip.Dialogs"
           elementFormDefault="qualified">
  <xs:element name="Dialog">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="root">
          <xs:attribute name="name" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Set">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="Dialog"/>
        <xs:element ref="PartDialog"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="PartDialog">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="root">
          <xs:attribute name="ref" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="root">
    <xs:sequence>
      <xs:element ref="Phrase" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Phrase">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="speech">
          <xs:attribute name="author" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Answer">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="speech">
          <xs:attribute name="line" type="xs:string" use="required"/>
          <xs:attribute name="ref" type="xs:anyURI"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="speech">
    <xs:sequence>
      <xs:element name="Text" type="xs:normalizedString"/>
      <xs:any minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lay" type="xs:string"/>
  </xs:complexType>

</xs:schema>

=== KolkaMeister/museum-defender/Assets/DialogDatas/xml/NewCons.xml
<?xml version="1.0" encoding="utf-8" ?>
<Set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:HistoryTrip.Dialogs"
     xsi:schemaLocation="urn:HistoryTrip.Dialogs dialog.xsd">
  <Dialog name="NewCons">
    <Phrase author="Action">
      <Text>Выберите дейсвтие</Text>
      <Answer line="1">
        <Text>Взять квест</Text>
      </Answer>
    </Phrase>
    <Phrase author="Олег" lay="1">
      <Text>Держи квест</Text>
    </Phrase>
    <Phrase author="Игрок" tag="End">
      <Text>Спасибо, Великий Князь!</Text>
    </Phrase>
  </Dialog>
</Set>

=== KolkaMeister/museum-defender/Assets/StreamingAssets/BubbleDialog.xml
<?xml version="1.0" encoding="utf-8"?>
<Set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:HistoryTrip.Dialogs"
     xsi:schemaLocation="urn:HistoryTrip.Dialogs dialog.xsd">
  <Dialog name="bubble 1">
    <Phrase author="1">
      <Text>Hi!</Text>
    </Phrase>
    <Phrase author="2">
      <Text>Hello, my friend</Text>
    </Phrase>
    <Phrase author="1">
      <Text>Do you sell fish?</Text>
    </Phrase>
    <Phrase author="2">
      <Text>No, just show</Text>
    </Phrase>
    <Phrase author="1">
      <Text>Beautiful!</Text>
    </Phrase>
  </Dialog>
</Set>

=== KolkaMeister/museum-defender/Assets/DialogDatas/xml/OlegDialog.xml
<?xml version="1.0" encoding="utf-8" ?>
<Set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:HistoryTrip.Dialogs"
     xsi:schemaLocation="urn:HistoryTrip.Dialogs dialog.xsd">
  <Dialog name="Oleg">
    <Phrase author="Игрок">
      <Text>Великий Кнаязь Олег. Могу ли я задать вам несколько вопросов о нашей битве с Византией?</Text>
      <Answer line="1">
        <Text>Как проходит подготовка к походу на Византию?</Text>
      </Answer>
      <Answer line="2">
        <Text>Какие земли могут быть нашими союзниками в этой битве?</Text>
      </Answer>
      <Answer line="3">
        <Text>Как мы собираемся действовать в походе против Византии?</Text>
      </Answer>
    </Phrase>
    <Phrase author="Олег" lay="1">
      <Text>Подготовка идет полным ходом. Наши воины полны решимости и готовы отдать свои жизни за русские земли.</Text>
    </Phrase>
    <Phrase author="Олег" lay="2">
      <Text>Союзники - это важная часть нашего замысла. Мы договорились с племенами восточных славян, они обещают нам помочь.</Text>
    </Phrase>
    <Phrase author="Олег" lay="3">
      <Text>Мы зайдем с моря и атакуем на кораблях. Будем применять наши суда для перекрытия морских торговых путей. Также мы направим их на вражеские корабли и гавани, чтобы нанести удар по экономике Византии и ослабить ее оборону.</Text>
    </Phrase>
    <Phrase author="Олег" lay="3">
      <Text>Кроме того, будем внезапно атаковать на различных направлениях, чтобы заставить Византию сдать свои силы и ресурсы. Наша цель - добиться победы в этой войне и защитить наши земли и народ от врага.</Text>
    </Phrase>
    <Phrase author="Игрок">
      <Text>Спасибо, Великий Князь!</Text>
    </Phrase>
  </Dialog>
</Set>

=== KolkaMeister/museum-defender/Assets/StreamingAssets/BubbleDialog2.xml
<?xml version="1.0" encoding="utf-8"?>
<Set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:HistoryTrip.Dialogs"
     xsi:schemaLocation="urn:HistoryTrip.Dialogs dialog.xsd">
  <Dialog name="bubble 2">
    <Phrase author="1">
      <Text>Good morning, how long time ago have you stood here?</Text>
    </Phrase>
    <Phrase author="2">
      <Text>I don't know. I think more than usually</Text>
    </Phrase>
    <Phrase author="2">
      <Text>Why have you come to me?</Text>
    </Phrase>
    <Phrase author="1">
      <Text>I have something...</Text>
    </Phrase>
    <Phrase author="2">
      <Text>So, what is there?</Text>
    </Phrase>
    <Phrase author="1">
      <Text>One red and one blue</Text>
    </Phrase>
    <Phrase author="1">
      <Text>Which will you choose?</Text>
    </Phrase>
    <Phrase author="2">
      <Text>Maybe blue</Text>
    </Phrase>
    <Phrase author="1">
      <Text>Ooookey...</Text>
    </Phrase>
  </Dialog>
</Set>
